services:
  openvpn:
    image: xinglinglove1029/openvpn:latest
    build:
      context: .
      dockerfile: build/Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "1194:1194/udp"
      - "8888:8888"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      OVPN_GATEWAY: "true"
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
